### ISSUE TITLE
Footer needs "responsified"

### ISSUE THREAD

**Issue by wion** [content-strategy-forum/csf-website#13]
Content in the website footer needs to adapt to phone displays better:

1. Links list needs to span width, and links need blocked to touch them easier.
2. Copyright needs to slip under links list and span width.

![article-full-phone-04](https://cloud.githubusercontent.com/assets/948658/12057159/6163c050-af3e-11e5-9060-925905a9a732.jpg)

The red area at bottom indicates position of sponsor names/logos. How do they display on wider screens?

**Comment by kevinpotts** [comment]
This issue will be fixed when we implement new footer design. See Slack upload for mockup.

**Comment by wion** [comment]
@kevinpotts I'm assuming your taking this one. When you've committed changes, assign this issue back to me to check how it looks before going live (assuming you don't have a local database setup by that point).

**Comment by wion** [comment]
I corrected sock links alignment, which were not centered in mobile.
