### ISSUE TITLE
Homepage: machine recognition of identity and metadata

### ISSUE THREAD

**Issue by wion** [content-strategy-forum/csf-website#17]
@maniqui, @kevinpotts, @andrewnhem...

Something about the homepage needs changed so that "machines" identify and display it correctly. Here's a couple of examples of the problem...

LinkedIn sees it like this, which is okay except the logo is not being picked up as the image:

![screen shot 2016-01-10 at 14 00 48](https://cloud.githubusercontent.com/assets/948658/12262718/d07d5092-b929-11e5-8f53-c57b755ecc86.png)

Google+ has the image problem too, but also the metadata wonky. 

![screen shot 2016-01-12 at 12 35 33](https://cloud.githubusercontent.com/assets/948658/12262725/e455322e-b929-11e5-8f78-fb660a4756b4.png)

Something like this is what I would expect to see in Google+, but with CSF details showing:

![screen shot 2016-01-12 at 12 47 57](https://cloud.githubusercontent.com/assets/948658/12262842/d491886e-b92a-11e5-96f3-51e26c1f1e87.png)

How do we fix this?

**Comment by maniqui** [comment]
@wion,
I've pushed a new branch (`17_homepage_metadata`) with a fix. 
I'd suggest you to review it and, if everything is OK, to merge it back to branch `master`.
If you need guidance with some git-fu, let me know and then we can meet at Slack.

**Comment by wion** [comment]
A whole new branch for a metadata fix? Must be some big shit. ;)
I'll have a looksie.

**Comment by maniqui** [comment]
Hehehe :)
No, not really big. Just [a few code of lines](https://github.com/content-strategy-forum/csf-website/blob/17_homepage_metadata/assets/templates/forms/head-metadata.misc.txp#L8-L18)

But I thought it was a good chance for all to practice & learn a branching/reviewing/merging workflow ;)

In Git, branches are cheap (really easy to create/share/delete), so using them adds no overhead at all, and in fact, it usually promotes a good workflow: hot-fixes/bug-hunting/new-features are done in topic branches and then merged back to branch master.

**Comment by wion** [comment]
> But I thought it was a good chance for all to practice & learn a branching/reviewing/merging workflow ;)

@maniqui, 

Truth is, I have a *lot* to do at the moment (a lot of copy editing work), both with CSF and outside of it. If you think the fixes will work, just merge them back to master, please, and let's find out. I haven't used Git on command-line yet and I don't have the time right now to explore it. Some day, I promise.

Btw, when Txp 4.6 comes out and we  update, I expect some more architecture changes as a result. One example is removing arc_meta because Txp will natively provide for the same fields in admin side. That kind of thing. Hopefully the new native metadata fields will "suck in" any arc_meta data, but I don't think we can count on that, which means perhaps a lot of manual editing in the admin-side; copy/pasting arc_meta text to the new native fields, _then_ removing arc_meta. Something like that.
