### ISSUE TITLE
Add gbp_permanent_link and gbp_admin_library installers to repo

### ISSUE THREAD

**Issue by maniqui** [content-strategy-forum/csf-website#7]
As we need them for the `/people` section and permalinks to each member's profile to work properly.
Also, include the SQL code that needs to be executed to add the corresponding Permanent Links rules.

**Comment by wion** [comment]
Status? Can we close this?

**Comment by maniqui** [comment]
@wion I've just added them and closed this ticket. 
Also, this is the SQL that has to be executed for adding the corresponding Permanent Links rules. 
Where is the best place to add it? Maybe to a README file in the `assets/plugins/` folder?

```sql
INSERT INTO `txp_prefs` (`prefs_id`, `name`, `val`, `type`, `event`, `html`, `position`, `user_name`) VALUES
(1,	'gbp_permanent_links_5242c4fa76b7f_3',	';s:0:\"\";s:5:\"regex\";s:4:\"(.*)\";s:4:\"text\";s:0:\"\";}}}',	2,	'permlinks',	'gbp_partial',	0,	''),
(1,	'gbp_permanent_links_5242c4fa76b7f_2',	's:0:\"\";s:6:\"prefix\";s:0:\"\";s:6:\"suffix\";s:0:\"\";s:5:\"regex\";s:0:\"\";s:4:\"text\";s:0:\"\";}i:1;a:8:{s:4:\"type\";s:5:\"regex\";s:6:\"custom\";s:0:\"\";s:8:\"category\";s:0:\"\";s:4:\"name\";s:6:\"member\";s:6:\"prefix\";s:0:\"\";s:6:\"suffix\"',	2,	'permlinks',	'gbp_partial',	0,	''),
(1,	'gbp_permanent_links_5242c4fa76b7f_1',	'ry\";s:0:\"\";s:8:\"des_page\";s:0:\"\";s:12:\"des_permlink\";s:0:\"\";s:8:\"des_feed\";s:0:\"\";s:12:\"des_location\";s:0:\"\";}s:10:\"components\";a:2:{i:0;a:8:{s:4:\"type\";s:7:\"section\";s:6:\"custom\";s:0:\"\";s:8:\"category\";s:0:\"\";s:4:\"name\";',	2,	'permlinks',	'gbp_partial',	0,	''),
(1,	'gbp_permanent_links_5242c4fa76b7f',	'a:2:{s:8:\"settings\";a:11:{s:7:\"pl_name\";s:11:\"bio-profile\";s:13:\"pl_precedence\";s:1:\"0\";s:10:\"pl_preview\";s:13:\"section/(.*)/\";s:11:\"con_section\";s:6:\"people\";s:12:\"con_category\";s:0:\"\";s:11:\"des_section\";s:0:\"\";s:12:\"des_catego',	2,	'permlinks',	'gbp_serialized',	0,	''),
(1,	'gbp_permanent_links_5247769eca3ff_2',	'name\";s:0:\"\";s:6:\"prefix\";s:0:\"\";s:6:\"suffix\";s:0:\"\";s:5:\"regex\";s:0:\"\";s:4:\"text\";s:0:\"\";}i:1;a:8:{s:4:\"type\";s:8:\"category\";s:6:\"custom\";s:0:\"\";s:8:\"category\";s:1:\"1\";s:4:\"name\";s:0:\"\";s:6:\"prefix\";s:0:\"\";s:6:\"suf',	2,	'permlinks',	'gbp_partial',	0,	''),
(1,	'gbp_permanent_links_5247769eca3ff_1',	'_category\";s:0:\"\";s:8:\"des_page\";s:0:\"\";s:12:\"des_permlink\";s:0:\"\";s:8:\"des_feed\";s:0:\"\";s:12:\"des_location\";s:0:\"\";}s:10:\"components\";a:2:{i:0;a:8:{s:4:\"type\";s:7:\"section\";s:6:\"custom\";s:0:\"\";s:8:\"category\";s:0:\"\";s:4:\"',	2,	'permlinks',	'gbp_partial',	0,	''),
(1,	'gbp_permanent_links_5247769eca3ff',	'a:2:{s:8:\"settings\";a:11:{s:7:\"pl_name\";s:14:\"Category links\";s:13:\"pl_precedence\";s:1:\"0\";s:10:\"pl_preview\";s:17:\"section/category/\";s:11:\"con_section\";s:6:\"topics\";s:12:\"con_category\";s:0:\"\";s:11:\"des_section\";s:0:\"\";s:12:\"des',	2,	'permlinks',	'gbp_serialized',	0,	''),
(1,	'gbp_permanent_links_5247769eca3ff_3',	'fix\";s:0:\"\";s:5:\"regex\";s:0:\"\";s:4:\"text\";s:0:\"\";}}}',	2,	'permlinks',	'gbp_partial',	0,	'');
```

**Comment by wion** [comment]
@maniqui, I guess. 

Out of curiosity, is this new since the original code for people profiles? Or was it there originally from the TXP Mag code I pulled (Stef's work), and later screwed up when removing the gbp_pl plugin? 

In any case, I feel the ideal situation, at some point, is to not rely on gbp_permanent_links. If that means changing the architecture a bit and redirecting /people/first-name URLs to something new, that's fine. Much better than unnecessary plugins and complicated scripts to remember, IMO.

**Comment by maniqui** [comment]
> Out of curiosity, is this new since the original code for people profiles? Or was it there originally from the TXP Mag code I pulled (Stef's work), and later screwed up when removing the gbp_pl plugin?

Not sure if I'm understanding the questions. The related code in the page template (`people.txt`) is the original one. 
In [the referred commit](https://github.com/content-strategy-forum/csf-website/commit/874bd9459662f4725049488d6f11fd91aacfe274) I've just only added the plugin installers. I've also published the SQL statements in the above comment, as it's the "missing piece" for everything to work.
So, with the plugin installers and the SQL code, anyone setting up a copy of the CSF website could have a fully functional website, with the `/people` section working properly.

> In any case, I feel the ideal situation, at some point, is to not rely on gbp_permanent_links. If that means changing the architecture a bit and redirecting /people/first-name URLs to something new, that's fine. Much better than unnecessary plugins and complicated scripts to remember, IMO.

Agree.

**Comment by wion** [comment]
I was referring to, and curious about, the "SQL statements". I don't remember having ever had to do that before.

**Comment by maniqui** [comment]
Ah, yes.
As we usually import/export full dumps of the database, those dumps already include the above SQL statements. Those are, basically, the gbp_permanent_links rules (which were initially created via the TXP Admin).
I've "isolated" them in the above SQL statement, so if anyone wants to set up a copy of the CSF website _without_ having the full database (ie. starting for a "blank slate"), he still has the chance to add the gbp_permanent_links rules needed for the People section to work properly. That being said, I'm not sure if there is going to be anyone creating a copy of the CSF website from a "blank slate" (that is, without having a full copy of the database). You tell me...

**Comment by wion** [comment]
> I've "isolated" them in the above SQL statement, so if anyone wants to set up a copy of the CSF website without having the full database (ie. starting for a "blank slate"), he still has the chance to add the gbp_permanent_links rules needed for the People section to work properly.

Okay. Nice thinking. As mentioned, though, I'd like to move away from reliance on the gbp_pl plugin, so we'll consider this temporary. Thanks for covering tracks though. I do like that.

> That being said, I'm not sure if there is going to be anyone creating a copy of the CSF website from a "blank slate" (that is, without having a full copy of the database). You tell me...

Doubtful. And we won't be making the DB public. The point of the install files is for front-end inspiration and architecture learning only.
